### PR TITLE
Initialize the USTC2015 meetup resources

### PR DESCRIPTION
**Pull request by i2000s**
Basically, I add the GSoC 2015 project doc to the README file and include my talk's slides to the repo.

@amitjamadagni can you double check the changes and add your materials in a proper folder and link them back in the README doc? Notice that I have removed a special character in the filename of your GSoC proposal to make it compatible with Windows OS. You should be able to merge the PR first. @Roger-luo will add links of the talk records to the README when he finishes editing works. Thanks.

### CODE REVIEW

**Comment by amitjamadagni** [comment]
@i2000s sorry for the delay ! But I was wondering if there was a way to add files to this PR ?! Also if that is not possible can I close it and create a final PR which has all the contents ?!

**Comment by i2000s** [comment]
No worry, I have been busy these days as well. Check out [this instruction](https://help.github.com/articles/checking-out-pull-requests-locally/) on editing PR locally. I should create a new branch before. Anyway, I let you try out the new trick :smile:

**Comment by amitjamadagni** [comment]
@i2000s  I have created a branch on my fork and have added all the files, in addition to the already existing ones. I guess I have to send in a pull request to your master with the changes and then we could merge it, instead of this may be we could close this and have a new PR with all the changes ?!

**Comment by i2000s** [comment]
@amitjamadagni I am not sure which way works best. Please go ahead and try :smile_cat:

**Comment by Roger-luo** [comment]
@i2000s there is some problem with the video. I need to ask the cameraman for a new download. This may cause this work delayed to about 20th,Feb. But I start working on the news and Juliacon videos. Sorry for that.

**Comment by i2000s** [comment]
@Roger-luo That is ok. Thank you for making videos for the community!

**Pull request merged**
