### PR TITLE
USTC Meetup post, all talks posted

### PR DESCRIPTION
**Pull request by amitjamadagni**
@i2000s This PR has all the additions from the previous PR ! Sorry I may have to close the previous one and may be if you could review this, I will just merge it :)

### CODE REVIEW

**Comment by i2000s** [comment]
@amitjamadagni I am not sure what happened to the *.md files in your commit. Did you change the line-endings? I think I have defined the line-ending to be linux file style in the git ignore files. Another thing to add is the link of your talk materials in the README doc. Otherwise, all looks good. 

And yeah, close the previous PR. Thank you.

**Comment by i2000s** [comment]
@amitjamadagni I think I have understood what happened to the BerkeleyTalk1 files. You may want to copy my `.gitattributes` file in the root directory to the BerkeleyTalk1 folder as well, or merge the content of the `.gitignore` file in the BerkeleyTalk1 folder to the root and delete the subfolder ones. That way, all line endings will be consistent and independent from local operating systems.

**Comment by amitjamadagni** [comment]
@i2000s  I am unable to rebase and squash the commits to a single commit (the problem is that I try to stash the changes which are reflected in the README and they just dont stash, to proceed with the rebase). Any help here would be really great :-).

**Comment by i2000s** [comment]
I will merge it for now. Future changes can go for separated commits. Sorry for the delay.

**Pull request merged**
